styles added
ok-technopolis-2020/Zakharova_Alena pull request #2
Opened 2020-10-16 10:10 UTC by alyonazakharova

2020-10-16 12:35 UTC, fromanywhere requested changes

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    font-family: Roboto;
Робото — гротеск, а браузер по дефолту рисует антиквой. Значит, пока шрифт не прогрузится, будет антиква, а потом оно рывком перерисуется. Чтобы такого не было, сюда дописывают хотя бы семейство

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    letter-spacing: -2.5px;
не надо таким заниматься

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    height: 402px;
ну, нет, фиксированные размеры здесь не подходят — элементы списка же могут добавляться. Кстати, заодно можно подумать о том, что будет, если элементов вообще не будет — макет здесь дает свободу

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    position: absolute;
от какого элемента будем позиционироваться в этом случае, почему и зачем?

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    box-shadow: inset 0px -1px 0px #E6E6E6;
фигма врет, здесь лучше бордером

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    background: url(../icons/select-all.png) no-repeat;
а что с ретиной?

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +	height: 16px;
вот оно, начинается. Потом чтобы в такую кнопку попасть, нужно быть снайпером. Максимизируем область клика

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    letter-spacing: -0.6px;
нет

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    letter-spacing: -0.6px;
ну пожалуйста

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    letter-spacing: -0.35px;
не надо

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    letter-spacing: -0.35px;
говорил на лекции специально

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    /*ничего умнее чтобы убрать крестик к правому краю в голову не пришло*/
use flex

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    /*не знаю, что сюда написать, но оно делает то, что я хочу*/
приятно, когда css угадывает желания
но в продакшне так не пишут

2020-10-16 12:35 UTC, fromanywhere commented on styles/style.css
> +    width: 562px;
никаких жестких размеров. Потом адаптивная верстка накажет. Растягиваемся под родителя

2020-10-22 21:07 UTC, alyonazakharova commented on styles/style.css
> +    height: 402px;
из-за того что футер находится не сразу за последним таском, а между ними есть какое-то пространство, мне показалось, что для основного блока пойдет фиксированный размер. то есть если элементов вообще не будет, между полем для добавления и футером просто будет пустое пространство, а если тасков будет много, то можно будет скроллить внутри основного блока.
но раз вы говорите, что фиксированнный размер не подходит -- исправлю, правда, пока нет идей как(((

2020-10-23 13:09 UTC, fromanywhere requested changes
Вообще при всех своеобразностях в верстке я должен признать, что визуально оно выглядит близко к макету. Ну, относительно. То есть в вебстудии начального уровня за это можно было бы даже просить деньги (но только в рублях, на аутсорс бы не взяли)

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +    height: 402px;
скролл засчет общего, на body
Поинт про схлоп справедливый, min-height будет лучше. Туда, кстати, можно вообще поставить заглушку будет через :empty

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +    width: 100%;
высота 
![image](https://user-images.githubusercontent.com/1042969/97006725-f2301c80-1548-11eb-8a4d-073e1794f86e.png)

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +    visibility: hidden;
площадь клика делаем больше 
![image](https://user-images.githubusercontent.com/1042969/97006804-0ffd8180-1549-11eb-8e28-624bea65525e.png)

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +li:hover .remove-btn {
фокус потерялся

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +	display: none;
не могу попасть сюда с клавиатуры

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +	border: 1px solid #EBDFDF;
Можно увидеть, что прыгают при переключении
![screencast 2020-10-23 16-03-38](https://user-images.githubusercontent.com/1042969/97007073-7d111700-1549-11eb-9d2b-1c357f1ccdc3.gif)

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +	width: 35%;
почему так?

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +    height: 9.5%;
ну, нет, какие проценты )

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +    width: 100%;
так ли это нужно?

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +    height: 14.5%;
ну, нет, зачем

2020-10-23 13:09 UTC, fromanywhere commented on styles/style.css
> +    box-shadow: inset 0px -1px 0px #E6E6E6;
учимся делать бордером, несмотря на то, что фигма говорит тенью
тени будут тормозить на рендере, потом на более или менее большом кол-ве элементов будет заметно

2020-10-26 20:32 UTC, fromanywhere requested changes

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +    border-spacing: 0;
это не нужно

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +/*а чтобы проверить, что оно работает, надо купить мак..?*/
![image](https://user-images.githubusercontent.com/1042969/97224499-4275db80-17e2-11eb-8a61-10a319733e63.png)

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +    height: 100%;
![image](https://user-images.githubusercontent.com/1042969/97224701-94b6fc80-17e2-11eb-963b-275b50ff8a56.png)

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +    /*замечание про фиксированные размеры помню, просто пока не знаю, как это решить*/
ну, так норм

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +    position: sticky;
фон нужно не забыть, просвечивает

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +input[type="text"] {
Начинаем мигрировать на бэм

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +    min-height: 296px;
это не понадобится

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +    width: 100%
так не очень. flex-grow: 1 + min-width: 0;

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +}
там еще где-то тень у формы внизу

2020-10-26 20:32 UTC, fromanywhere commented on styles/style.css
> +    	width: 28px;
обычно под ретину убирают только сам путь до картинки + её размер, остальную геометрию обычно дублировать не приходится

2020-10-28 08:45 UTC, alyonazakharova commented
кажется, я немного запуталась с файловой организацией и блоками внутри блоков. еще почитаю что-нибудь, подумаю и постараюсь исправить в ближайшее время

2020-10-30 10:35 UTC, fromanywhere requested changes
Почти хорошо. С разбиением на компоненты оверкилл, но это пусть будет пока так, потом разберемся

2020-10-30 10:35 UTC, fromanywhere commented on styles/task/__button/task__button.css
> +    .task__button {
Имеет смысл проверить всё это под ретиной, потому что вроде написано ок, только позиционируется 
![image](https://user-images.githubusercontent.com/1042969/97694991-65d7a980-1ab4-11eb-9f19-baae550e519f.png)

2020-10-30 10:35 UTC, fromanywhere commented on styles/task/__status-icon/task__status-icon.css
> +    ..task__checkbox:checked + .task__status-icon {
опечатка, поэтому не работает

2020-10-30 10:35 UTC, fromanywhere commented on styles/style.css
> +    border-top: 1px solid var(--border-color);
одна из границ лишняя )

2020-10-30 10:35 UTC, fromanywhere commented on styles/task/__button/task__button.css
> +.item:hover .task__button {
на фокус бы тоже, сейчас с клавиатуры не показывается

2020-10-30 11:05 UTC, alyonazakharova commented on styles/task/__button/task__button.css
> +    .task__button {
добавила `background-position: center;` для ретины, вроде как это должно было исправить проблему.
но как вообще лучше проверять, что на ретине все будет нормально выглядеть?

2020-10-30 11:06 UTC, alyonazakharova commented on styles/style.css
> +    border-top: 1px solid var(--border-color);
справедливо...

2020-10-31 11:28 UTC, fromanywhere requested changes
Всё очень здорово, есть пара моментов: 
![image](https://user-images.githubusercontent.com/1042969/97777687-ee248000-1b82-11eb-9918-4fdb3ec7e390.png)

1) на .task__text лучше не ширину в 100%, а `flex-grow: 1;` . Отломаются переносы, чиним их `word-break: break-word;`

2) Теперь скукоживает радиокнопки .task__status-icon. Понятно, что в первую очередь `flex-shrink: 0`. Потом видно, что они какие-то некруглые, что неудивительно — ширина и высота разные. Ну, пусть ширина тоже будет `width: 33px;`, хотя нечетные значения — это всегда немного опасно. Скомпенсируем выравнивание `margin-left: -24px;`

3) Чиним крестик .task__button `flex-shrink: 0`

4) Чиним галочку на ретине:
`
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)
.task__checkbox:checked + .task__status-icon {
background-size: 20px 20px;
    background-position: 50% 50%;
}
`

5) На узком экране режется левый край формы. .todo-app { min-width: 570px; }, чтобы до этого не доходило

6) Тени под формой:

`
.main-container {  position: relative }
.main-container::before {
    content: '';
    position: absolute;
    top: 100%;
    left: 2px;
    right: 2px;
    height: 5px;
    z-index: -1;
    background-color: #fff;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
}
.main-container::after {
    content: '';
    position: absolute;
    top: 100%;
    left: 4px;
    right: 4px;
    height: 10px;
    z-index: -2;
    background-color: #fff;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
}
`

Работа готова!

2020-11-01 11:42 UTC, fromanywhere approved these changes
Класс

2020-11-02 06:52 UTC, merged